services:
  - type: web
    name: billbuster
    env: python
    buildCommand: |
      pip install -r server/requirements.txt
      cd client && npm install
      cd client && npm install react-dropzone tesseract.js framer-motion @heroicons/react
      cd client && npm run build
    startCommand: cd server && gunicorn wsgi:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --log-level debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 16.0.0
      - key: REACT_APP_API_URL
        value: https://billbuster.onrender.com
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /api/*
        destination: /api/:splat
      - type: rewrite
        source: /*
        destination: /index.html
